# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: edge
name: test_utils
version: 0.1.0
readme: README.md
authors:
  - Ansible Edge Automation Working Group (github.com/ansible/community/wiki/Edge-Automation)
description: null
license_file: LICENSE
repository: https://github.com/ansible-collections/edge.test_utils
#documentation: https://github.com/ansible-collection-migration/edge.test_utils/tree/main/docs
homepage: https://github.com/ansible-collections/edge.test_utils
issues: https://github.com/ansible-collections/edge.test_utils/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
